spec:
  inputs:
    action:
    environment:
---
stages:
  - manage

variables:
  ACTION: $[[ inputs.action ]]
  ENVIRONMENT: $[[ inputs.environment ]]

.auth: &auth
  image: registry.gitlab.com/malikcherfi/simplon-22-pyweb-malik/azure-docker-cli:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: "https://gitlab.com"
  before_script:
    - az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $GITLAB_OIDC_TOKEN

create-container-app:
  stage: manage
  <<: *auth
  script:
    - chmod +x scripts/create-container-app.sh
    - ./scripts/create-container-app.sh $ENVIRONMENT
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $ACTION == "create"

delete-container-app:
  stage: manage
  <<: *auth
  script:
    - chmod +x scripts/delete-container-app.sh
    - ./scripts/delete-container-app.sh $ENVIRONMENT
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $ACTION == "delete"
