spec:
  inputs:
    action:
      type: string
      description: "Action Container App"
      default: none
      options: ["none", "create", "delete", "deploy"]
    environment:
      type: string
      description: "Environment"
      default: staging
      options: ["staging", "production"]
---
include:
  - local: ".gitlab/workflows/.gitlab-cd.yml"
    inputs:
      action: $[[ inputs.action ]]
      environment: $[[ inputs.environment ]]
  - local: ".gitlab/workflows/.gitlab-ressource-handler.yml"
    inputs:
      action: $[[ inputs.action ]]
      environment: $[[ inputs.environment ]]

stages:
  # - lint
  # - sast
  - deploy
  - build
  - manage

# flake8:
#   stage: lint
#   image: python:3.14
#   script:
#     - pip install flake8
#     - flake8 app.py
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "web"
#       when: manual
#     - if: $CI_PIPELINE_SOURCE == "push"

# bandit:
#   stage: sast
#   image: python:3.14
#   script:
#     - pip install bandit
#     - bandit -r app.py -ll
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "web"
#       when: manual
#     - if: $CI_PIPELINE_SOURCE == "push"
