spec:
  inputs:
    action:
      description: "Action Container App"
      options:
        - create
        - delete
---
stages:
  - manage

.auth: &auth
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: "https://gitlab.com"
  before_script:
    - az login --service-principal
      -u $AZURE_CLIENT_ID
      -t $AZURE_TENANT_ID
      --federated-token $GITLAB_OIDC_TOKEN

create-container-app:
  stage: manage
  <<: *auth
  script:
    - chmod +x scripts/create-container-app.sh
    - ./scripts/create-container-app.sh
  rules:
    - if: $[[ inputs.action ]] == "create"

delete-container-app:
  stage: manage
  <<: *auth
  script:
    - chmod +x scripts/delete-container-app.sh
    - ./scripts/delete-container-app.sh
  rules:
    - if: $[[ inputs.action ]] == "delete"
